// Batch 2 exercises for the N4 て-form/た-form compound points (ex8–ex11).
// Sidecar to grammar/n4/batch1-te-ta.ts — see CONTENT_GUIDE.md "Sidecar files".

import type { Exercise } from "../../types";

export const exercises: Exercise[] = [
  // -------------------------------------------------------------------
  // n4.ta-koto-ga-aru
  // -------------------------------------------------------------------
  {
    id: "n4.ta-koto-ga-aru.ex8",
    grammarPointId: "n4.ta-koto-ga-aru",
    source: "bank",
    kind: "mcq",
    question: "私[わたし]は飛行機[ひこうき]に一度[いちど]も＿＿ことがありません。",
    choices: ["乗[の]った", "乗[の]る", "乗[の]って", "乗[の]ります"],
    correctIndex: 0,
    explanation: "〜たことがない (never have done ~) needs the plain past た-form immediately before ことがありません: 乗った。",
  },
  {
    id: "n4.ta-koto-ga-aru.ex9",
    grammarPointId: "n4.ta-koto-ga-aru",
    source: "bank",
    kind: "ordering",
    segments: ["彼女[かのじょ]は", "有名人[ゆうめいじん]に", "会[あ]ったことが", "あります。"],
    starIndex: 2,
    translationEn: "She has met a famous person before.",
  },
  {
    id: "n4.ta-koto-ga-aru.ex10",
    grammarPointId: "n4.ta-koto-ga-aru",
    source: "bank",
    kind: "transformation",
    sourceJa: "スキーをしました。",
    instruction: "Rewrite as a statement of past experience using 〜たことがある。",
    targetLabel: "〜たことがある",
    accepted: ["スキーをしたことがあります。", "スキーをしたことがある。"],
    translationEn: "I have skied before.",
  },
  {
    id: "n4.ta-koto-ga-aru.ex11",
    grammarPointId: "n4.ta-koto-ga-aru",
    source: "bank",
    kind: "transformation",
    sourceJa: "彼[かれ]はコーヒーを飲[の]みません。",
    instruction: "Rewrite to say he has never had this experience, using 〜たことがない。",
    targetLabel: "〜たことがない",
    accepted: ["彼[かれ]はコーヒーを飲[の]んだことがありません。", "彼[かれ]はコーヒーを飲[の]んだことがない。"],
    translationEn: "He has never drunk coffee.",
  },

  // -------------------------------------------------------------------
  // n4.tari-tari
  // -------------------------------------------------------------------
  {
    id: "n4.tari-tari.ex8",
    grammarPointId: "n4.tari-tari",
    source: "bank",
    kind: "mcq",
    question: "暇[ひま]な時[とき]は、絵[え]を描[か]いたり、写真[しゃしん]を＿＿します。",
    choices: ["撮[と]る", "撮[と]ったり", "撮[と]って", "撮[と]ります"],
    correctIndex: 1,
    explanation: "Each item in the 〜たり〜たり list takes たり (撮ったり); only the final する carries tense, so the items themselves never switch to plain, て-, or ます-form.",
  },
  {
    id: "n4.tari-tari.ex9",
    grammarPointId: "n4.tari-tari",
    source: "bank",
    kind: "ordering",
    segments: ["公園[こうえん]で", "犬[いぬ]と", "散歩[さんぽ]したり", "遊[あそ]んだりします。"],
    starIndex: 2,
    translationEn: "I do things like walk and play with my dog at the park.",
  },
  {
    id: "n4.tari-tari.ex10",
    grammarPointId: "n4.tari-tari",
    source: "bank",
    kind: "transformation",
    sourceJa: "週末[しゅうまつ]は、ギターを弾[ひ]いて歌[うた]を歌[うた]います。",
    instruction: "Rewrite as a non-exhaustive list of activities using 〜たり〜たりする instead of a fixed て-form sequence.",
    targetLabel: "〜たり〜たりする",
    accepted: ["週末[しゅうまつ]は、ギターを弾[ひ]いたり歌[うた]を歌[うた]ったりします。", "週末[しゅうまつ]は、ギターを弾[ひ]いたり歌[うた]を歌[うた]ったりする。"],
    translationEn: "On weekends, I do things like play guitar and sing.",
  },
  {
    id: "n4.tari-tari.ex11",
    grammarPointId: "n4.tari-tari",
    source: "bank",
    kind: "transformation",
    sourceJa: "母[はは]は料理[りょうり]を作[つく]って、お菓子[かし]を焼[や]きました。",
    instruction: "Rewrite using 〜たり〜たりする to present these as a non-exhaustive sample of things she did, not a fixed sequence.",
    targetLabel: "〜たり〜たりする",
    accepted: ["母[はは]は料理[りょうり]を作[つく]ったり、お菓子[かし]を焼[や]いたりしました。", "母[はは]は料理[りょうり]を作[つく]ったり、お菓子[かし]を焼[や]いたりした。"],
    translationEn: "My mother did things like cook and bake sweets.",
  },

  // -------------------------------------------------------------------
  // n4.nagara
  // -------------------------------------------------------------------
  {
    id: "n4.nagara.ex8",
    grammarPointId: "n4.nagara",
    source: "bank",
    kind: "mcq",
    question: "スマートフォンを見[み]＿＿、歩[ある]かないでください。",
    choices: ["ないで", "ますが", "ながら", "ても"],
    correctIndex: 2,
    explanation: "ながら links two simultaneous actions by the same subject (見ながら歩く); the other options don't produce the 'while doing X' meaning this warning needs.",
  },
  {
    id: "n4.nagara.ex9",
    grammarPointId: "n4.nagara",
    source: "bank",
    kind: "ordering",
    segments: ["彼[かれ]は", "傘[かさ]を", "差[さ]しながら", "自転車[じてんしゃ]に乗[の]っています。"],
    starIndex: 2,
    translationEn: "He is riding a bicycle while holding an umbrella.",
  },
  {
    id: "n4.nagara.ex10",
    grammarPointId: "n4.nagara",
    source: "bank",
    kind: "transformation",
    sourceJa: "道[みち]を歩[ある]いて、パンを食[た]べました。",
    instruction: "Rewrite using 〜ながら to show the two actions happened at the same time, with eating as the main action.",
    targetLabel: "〜ながら",
    accepted: ["道[みち]を歩[ある]きながら、パンを食[た]べました。", "道[みち]を歩[ある]きながらパンを食[た]べました。"],
    translationEn: "I ate bread while walking along the street.",
  },
  {
    id: "n4.nagara.ex11",
    grammarPointId: "n4.nagara",
    source: "bank",
    kind: "transformation",
    sourceJa: "シャワーを浴[あ]びて、歌[うた]を歌[うた]いました。",
    instruction: "Rewrite using 〜ながら so that singing is the main action and showering is the background action.",
    targetLabel: "〜ながら",
    accepted: ["シャワーを浴[あ]びながら、歌[うた]を歌[うた]いました。", "シャワーを浴[あ]びながら歌[うた]を歌[うた]いました。"],
    translationEn: "I sang while taking a shower.",
  },

  // -------------------------------------------------------------------
  // n4.te-oku
  // -------------------------------------------------------------------
  {
    id: "n4.te-oku.ex8",
    grammarPointId: "n4.te-oku",
    source: "bank",
    kind: "mcq",
    question: "会議[かいぎ]の前[まえ]に、資料[しりょう]をコピー＿＿。",
    choices: ["します", "しました", "しておきます", "していました"],
    correctIndex: 2,
    explanation: "ておく marks doing something now in preparation for later (copies made ahead of the meeting); plain します/しました/していました all lack that forward-looking preparation nuance.",
  },
  {
    id: "n4.te-oku.ex9",
    grammarPointId: "n4.te-oku",
    source: "bank",
    kind: "ordering",
    segments: ["出[で]かける前[まえ]に、", "部屋[へや]の", "電気[でんき]を", "消[け]しておきました。"],
    starIndex: 2,
    translationEn: "I turned off the room's lights in advance before going out.",
  },
  {
    id: "n4.te-oku.ex10",
    grammarPointId: "n4.te-oku",
    source: "bank",
    kind: "transformation",
    sourceJa: "冷蔵庫[れいぞうこ]に牛乳[ぎゅうにゅう]を入[い]れました。",
    instruction: "Rewrite using 〜ておく to show the milk was put away in advance for later.",
    targetLabel: "〜ておく",
    accepted: ["冷蔵庫[れいぞうこ]に牛乳[ぎゅうにゅう]を入[い]れておきました。", "冷蔵庫[れいぞうこ]に牛乳[ぎゅうにゅう]を入[い]れておいた。"],
    translationEn: "I put the milk in the fridge in advance.",
  },
  {
    id: "n4.te-oku.ex11",
    grammarPointId: "n4.te-oku",
    source: "bank",
    kind: "transformation",
    sourceJa: "友達[ともだち]にメールを送[おく]りました。",
    instruction: "Rewrite using 〜ておく to show the email was sent proactively, ahead of time.",
    targetLabel: "〜ておく",
    accepted: ["友達[ともだち]にメールを送[おく]っておきました。", "友達[ともだち]にメールを送[おく]っておいた。"],
    translationEn: "I sent my friend an email ahead of time.",
  },

  // -------------------------------------------------------------------
  // n4.te-shimau
  // -------------------------------------------------------------------
  {
    id: "n4.te-shimau.ex8",
    grammarPointId: "n4.te-shimau",
    source: "bank",
    kind: "mcq",
    question: "財布[さいふ]を＿＿しまいました。",
    choices: ["落[お]とした", "落[お]として", "落[お]とす", "落[お]とします"],
    correctIndex: 1,
    explanation: "てしまう attaches to the て-form; 落として is the correct form immediately before しまいました。",
  },
  {
    id: "n4.te-shimau.ex9",
    grammarPointId: "n4.te-shimau",
    source: "bank",
    kind: "ordering",
    segments: ["料理[りょうり]をしていて、", "うっかり", "お皿[さら]を", "割[わ]ってしまいました。"],
    starIndex: 2,
    translationEn: "While cooking, I carelessly broke a plate.",
  },
  {
    id: "n4.te-shimau.ex10",
    grammarPointId: "n4.te-shimau",
    source: "bank",
    kind: "transformation",
    sourceJa: "大事[だいじ]な会議[かいぎ]に遅刻[ちこく]しました。",
    instruction: "Rewrite using 〜てしまう to add a nuance of regret.",
    targetLabel: "〜てしまう",
    accepted: ["大事[だいじ]な会議[かいぎ]に遅刻[ちこく]してしまいました。", "大事[だいじ]な会議[かいぎ]に遅刻[ちこく]してしまった。"],
    translationEn: "I ended up being late for an important meeting.",
  },
  {
    id: "n4.te-shimau.ex11",
    grammarPointId: "n4.te-shimau",
    source: "bank",
    kind: "transformation",
    sourceJa: "レポートを書[か]きました。",
    instruction: "Rewrite using 〜てしまう to emphasize that the report is now completely finished.",
    targetLabel: "〜てしまう",
    accepted: ["レポートを書[か]いてしまいました。", "レポートを書[か]いてしまった。"],
    translationEn: "I've gone ahead and finished writing the report.",
  },

  // -------------------------------------------------------------------
  // n4.te-miru
  // -------------------------------------------------------------------
  {
    id: "n4.te-miru.ex8",
    grammarPointId: "n4.te-miru",
    source: "bank",
    kind: "mcq",
    question: "一度[いちど]、着物[きもの]を＿＿たいです。",
    choices: ["着[き]て", "着[き]てみて", "着[き]てみる", "着[き]てみ"],
    correctIndex: 3,
    explanation: "〜てみたい needs てみ (て-form + み, dropping the final る) directly before たい: 着てみたい, not 着てみるたい or other endings.",
  },
  {
    id: "n4.te-miru.ex9",
    grammarPointId: "n4.te-miru",
    source: "bank",
    kind: "ordering",
    segments: ["友達[ともだち]から", "借[か]りた", "パソコンを", "使[つか]ってみました。"],
    starIndex: 2,
    translationEn: "I tried using the computer I borrowed from my friend.",
  },
  {
    id: "n4.te-miru.ex10",
    grammarPointId: "n4.te-miru",
    source: "bank",
    kind: "transformation",
    sourceJa: "初[はじ]めて一人[ひとり]で旅行[りょこう]をしました。",
    instruction: "Rewrite using 〜てみる to show you tried it out to see what it was like.",
    targetLabel: "〜てみる",
    accepted: ["初[はじ]めて一人[ひとり]で旅行[りょこう]をしてみました。", "初[はじ]めて一人[ひとり]で旅行[りょこう]をしてみた。"],
    translationEn: "I tried traveling alone for the first time (to see what it was like).",
  },
  {
    id: "n4.te-miru.ex11",
    grammarPointId: "n4.te-miru",
    source: "bank",
    kind: "transformation",
    sourceJa: "この本[ほん]を読[よ]みました。",
    instruction: "Rewrite using 〜てみる to show you read it to see what it was like.",
    targetLabel: "〜てみる",
    accepted: ["この本[ほん]を読[よ]んでみました。", "この本[ほん]を読[よ]んでみた。"],
    translationEn: "I tried reading this book (to see what it was like).",
  },

  // -------------------------------------------------------------------
  // n4.sugiru
  // -------------------------------------------------------------------
  {
    id: "n4.sugiru.ex8",
    grammarPointId: "n4.sugiru",
    source: "bank",
    kind: "mcq",
    question: "今日[きょう]は＿＿すぎて、休[やす]む時間[じかん]がありません。",
    choices: ["忙[いそが]しい", "忙[いそが]しく", "忙[いそが]しかった", "忙[いそが]し"],
    correctIndex: 3,
    explanation: "すぎる attaches to an い-adjective stem with the final い dropped: 忙しい→忙し+すぎる; the other choices keep too much of the adjective's own ending.",
  },
  {
    id: "n4.sugiru.ex9",
    grammarPointId: "n4.sugiru",
    source: "bank",
    kind: "ordering",
    segments: ["彼[かれ]は", "毎晩[まいばん]", "お金[かね]を", "使[つか]いすぎています。"],
    starIndex: 2,
    translationEn: "He spends too much money every night.",
  },
  {
    id: "n4.sugiru.ex10",
    grammarPointId: "n4.sugiru",
    source: "bank",
    kind: "transformation",
    sourceJa: "今日[きょう]は忙[いそが]しいです。",
    instruction: "Rewrite using 〜すぎる to say it's excessively busy — more than is reasonable.",
    targetLabel: "〜すぎる",
    accepted: ["今日[きょう]は忙[いそが]しすぎます。", "今日[きょう]は忙[いそが]しすぎる。"],
    translationEn: "Today is too busy.",
  },
  {
    id: "n4.sugiru.ex11",
    grammarPointId: "n4.sugiru",
    source: "bank",
    kind: "transformation",
    sourceJa: "今朝[けさ]、たくさん寝[ね]ました。",
    instruction: "Rewrite using 〜すぎる to say you overslept, replacing たくさん with the grammatical marker.",
    targetLabel: "〜すぎる",
    accepted: ["今朝[けさ]、寝[ね]すぎました。", "今朝[けさ]、寝[ね]すぎた。"],
    translationEn: "I overslept this morning.",
  },
];
