// Batch 2 exercises for the N4 seed points (ex8–ex11).
// Sidecar to grammar/n4/seed.ts — see CONTENT_GUIDE.md "Sidecar files".

import type { Exercise } from "../../types";

export const exercises: Exercise[] = [
  // -------------------------------------------------------------------
  // n4.potential
  // -------------------------------------------------------------------
  {
    id: "n4.potential.ex8",
    grammarPointId: "n4.potential",
    source: "bank",
    kind: "mcq",
    question: "駅[えき]の前[まえ]で三十分[さんじゅっぷん]＿＿か。",
    choices: ["待[ま]ちます", "待[ま]てます", "待[ま]たせます", "待[ま]てば"],
    correctIndex: 1,
    explanation:
      "待てます is the potential form of 待つ (can wait). 待ちます is plain non-past, 待たせます is causative, and 待てば is the ば-conditional.",
  },
  {
    id: "n4.potential.ex9",
    grammarPointId: "n4.potential",
    source: "bank",
    kind: "ordering",
    segments: ["一人[ひとり]でも、", "この問題[もんだい]が", "解[と]け", "ます。"],
    starIndex: 2,
    translationEn: "Even alone, I can solve this problem.",
  },
  {
    id: "n4.potential.ex10",
    grammarPointId: "n4.potential",
    source: "bank",
    kind: "transformation",
    sourceJa: "彼[かれ]はギターを弾[ひ]きます。",
    instruction: "Rewrite using the potential form.",
    targetLabel: "可能形",
    accepted: ["彼[かれ]はギターが弾[ひ]けます。", "彼[かれ]はギターを弾[ひ]けます。"],
    translationEn: "He can play the guitar.",
  },
  {
    id: "n4.potential.ex11",
    grammarPointId: "n4.potential",
    source: "bank",
    kind: "transformation",
    sourceJa: "兄[あに]は日本語[にほんご]の歌[うた]を歌[うた]います。",
    instruction: "Rewrite using the potential form.",
    targetLabel: "可能形",
    accepted: ["兄[あに]は日本語[にほんご]の歌[うた]が歌[うた]えます。", "兄[あに]は日本語[にほんご]の歌[うた]を歌[うた]えます。"],
    translationEn: "My older brother can sing Japanese songs.",
  },

  // -------------------------------------------------------------------
  // n4.passive
  // -------------------------------------------------------------------
  {
    id: "n4.passive.ex8",
    grammarPointId: "n4.passive",
    source: "bank",
    kind: "mcq",
    question: "私[わたし]は電車[でんしゃ]の中[なか]で、知[し]らない人[ひと]に＿＿。",
    choices: ["押[お]しました", "押[お]させました", "押[お]されました", "押[お]せました"],
    correctIndex: 2,
    explanation:
      "This is a suffering passive: the speaker was pushed by a stranger, so 押されました is correct. The others are active, causative, and potential.",
  },
  {
    id: "n4.passive.ex9",
    grammarPointId: "n4.passive",
    source: "bank",
    kind: "ordering",
    segments: ["この歌[うた]は", "世界中[せかいじゅう]の", "人々[ひとびと]に", "知[し]られています。"],
    starIndex: 2,
    translationEn: "This song is known by people all over the world.",
  },
  {
    id: "n4.passive.ex10",
    grammarPointId: "n4.passive",
    source: "bank",
    kind: "transformation",
    sourceJa: "泥棒[どろぼう]が私[わたし]の財布[さいふ]を盗[ぬす]みました。",
    instruction: "Rewrite as a passive sentence from the victim's point of view.",
    targetLabel: "受身形",
    accepted: ["私[わたし]は泥棒[どろぼう]に財布[さいふ]を盗[ぬす]まれました。", "泥棒[どろぼう]に財布[さいふ]を盗[ぬす]まれました。"],
    translationEn: "I had my wallet stolen by a thief.",
  },
  {
    id: "n4.passive.ex11",
    grammarPointId: "n4.passive",
    source: "bank",
    kind: "transformation",
    sourceJa: "多[おお]くの人[ひと]がこのアプリを利用[りよう]しています。",
    instruction: "Rewrite as a passive sentence, making the app the subject.",
    targetLabel: "受身形",
    accepted: ["このアプリは多[おお]くの人[ひと]に利用[りよう]されています。", "このアプリは多[おお]くの人[ひと]によって利用[りよう]されています。"],
    translationEn: "This app is used by a lot of people.",
  },

  // -------------------------------------------------------------------
  // n4.causative
  // -------------------------------------------------------------------
  {
    id: "n4.causative.ex8",
    grammarPointId: "n4.causative",
    source: "bank",
    kind: "mcq",
    question: "先生[せんせい]は学生[がくせい]＿＿作文[さくぶん]を書[か]かせました。",
    choices: ["は", "が", "で", "に"],
    correctIndex: 3,
    explanation: "書く already has an を object (作文を), so the causee (学生) is marked with に: 学生に作文を書かせる.",
  },
  {
    id: "n4.causative.ex9",
    grammarPointId: "n4.causative",
    source: "bank",
    kind: "ordering",
    segments: ["母[はは]は", "毎朝[まいあさ]", "子供[こども]に", "牛乳[ぎゅうにゅう]を", "飲[の]ませます。"],
    starIndex: 2,
    translationEn: "My mother makes her child drink milk every morning.",
  },
  {
    id: "n4.causative.ex10",
    grammarPointId: "n4.causative",
    source: "bank",
    kind: "transformation",
    sourceJa: "子供[こども]が早[はや]く寝[ね]ます。",
    instruction: "Rewrite as a causative sentence with 母は as the subject.",
    targetLabel: "使役形",
    accepted: ["母[はは]は子供[こども]を早[はや]く寝[ね]させます。"],
    translationEn: "The mother makes the child go to sleep early.",
  },
  {
    id: "n4.causative.ex11",
    grammarPointId: "n4.causative",
    source: "bank",
    kind: "transformation",
    sourceJa: "子供[こども]がピアノを弾[ひ]きます。",
    instruction: "Rewrite as a causative sentence with 先生は as the subject.",
    targetLabel: "使役形",
    accepted: ["先生[せんせい]は子供[こども]にピアノを弾[ひ]かせます。"],
    translationEn: "The teacher has the child play the piano.",
  },

  // -------------------------------------------------------------------
  // n4.volitional
  // -------------------------------------------------------------------
  {
    id: "n4.volitional.ex8",
    grammarPointId: "n4.volitional",
    source: "bank",
    kind: "mcq",
    question: "電車[でんしゃ]が来[く]る前[まえ]に、切符[きっぷ]を＿＿。",
    choices: ["買[か]おう", "買[か]う", "買[か]います", "買[か]えば"],
    correctIndex: 0,
    explanation: "The casual self-invitation 'let's buy the ticket' calls for the volitional form 買おう, not the dictionary form or ば-conditional.",
  },
  {
    id: "n4.volitional.ex9",
    grammarPointId: "n4.volitional",
    source: "bank",
    kind: "ordering",
    segments: ["今度[こんど]の", "土曜日[どようび]、", "みんなで", "海[うみ]に行[い]こう。"],
    starIndex: 2,
    translationEn: "Let's all go to the beach this coming Saturday.",
  },
  {
    id: "n4.volitional.ex10",
    grammarPointId: "n4.volitional",
    source: "bank",
    kind: "transformation",
    sourceJa: "来週[らいしゅう]、部屋[へや]を片付[かたづ]けます。",
    instruction: "Rewrite as a statement of intention using volitional + と思います.",
    targetLabel: "意向形",
    accepted: ["来週[らいしゅう]、部屋[へや]を片付[かたづ]けようと思[おも]います。", "来週[らいしゅう]、部屋[へや]を片付[かたづ]けようと思[おも]う。"],
    translationEn: "I think I'll tidy my room next week.",
  },
  {
    id: "n4.volitional.ex11",
    grammarPointId: "n4.volitional",
    source: "bank",
    kind: "transformation",
    sourceJa: "一緒[いっしょ]にコーヒーを飲[の]みます。",
    instruction: "Rewrite as a casual invitation using the volitional form.",
    targetLabel: "意向形",
    accepted: ["一緒[いっしょ]にコーヒーを飲[の]もう。", "一緒[いっしょ]にコーヒーを飲[の]もうよ。"],
    translationEn: "Let's drink coffee together.",
  },

  // -------------------------------------------------------------------
  // n4.ba-tara
  // -------------------------------------------------------------------
  {
    id: "n4.ba-tara.ex8",
    grammarPointId: "n4.ba-tara",
    source: "bank",
    kind: "mcq",
    question: "暇[ひま]＿＿、映画[えいが]を見[み]に行[い]きませんか。",
    choices: ["ければ", "なら", "たら", "えば"],
    correctIndex: 1,
    explanation: "Noun/な-adjective conditionals use なら (暇なら), not ければ (い-adjectives) or verb-specific ば/たら.",
  },
  {
    id: "n4.ba-tara.ex9",
    grammarPointId: "n4.ba-tara",
    source: "bank",
    kind: "ordering",
    segments: ["友達[ともだち]が", "来[き]たら、", "一緒[いっしょ]に", "晩[ばん]ご飯[はん]を食[た]べます。"],
    starIndex: 1,
    translationEn: "If my friend comes, we'll eat dinner together.",
  },
  {
    id: "n4.ba-tara.ex10",
    grammarPointId: "n4.ba-tara",
    source: "bank",
    kind: "transformation",
    sourceJa: "涼[すず]しかったら、散歩[さんぽ]に行[い]きます。",
    instruction: "Rewrite using ば instead of たら.",
    targetLabel: "ば形",
    accepted: ["涼[すず]しければ、散歩[さんぽ]に行[い]きます。"],
    translationEn: "If it's cool, I'll go for a walk.",
  },
  {
    id: "n4.ba-tara.ex11",
    grammarPointId: "n4.ba-tara",
    source: "bank",
    kind: "transformation",
    sourceJa: "疲[つか]れれば、早[はや]く休[やす]みます。",
    instruction: "Rewrite using たら instead of ば.",
    targetLabel: "たら形",
    accepted: ["疲[つか]れたら、早[はや]く休[やす]みます。"],
    translationEn: "If I get tired, I'll rest early.",
  },

  // -------------------------------------------------------------------
  // n4.nakereba-naranai
  // -------------------------------------------------------------------
  {
    id: "n4.nakereba-naranai.ex8",
    grammarPointId: "n4.nakereba-naranai",
    source: "bank",
    kind: "mcq",
    question: "明日[あした]は試験[しけん]があるので、今晩[こんばん]＿＿。",
    choices: ["早[はや]く寝[ね]てもいいです", "早[はや]く寝[ね]てはいけません", "早[はや]く寝[ね]なければなりません", "早[はや]く寝[ね]なくてもいいです"],
    correctIndex: 2,
    explanation: "Having an exam tomorrow creates an obligation, so 早く寝なければなりません (must sleep early) fits, not permission/prohibition/non-obligation.",
  },
  {
    id: "n4.nakereba-naranai.ex9",
    grammarPointId: "n4.nakereba-naranai",
    source: "bank",
    kind: "ordering",
    segments: ["毎日[まいにち]薬[くすり]を", "三回[さんかい]", "飲[の]まなければ", "いけません。"],
    starIndex: 2,
    translationEn: "I have to take medicine three times a day.",
  },
  {
    id: "n4.nakereba-naranai.ex10",
    grammarPointId: "n4.nakereba-naranai",
    source: "bank",
    kind: "transformation",
    sourceJa: "この書類[しょるい]にサインします。",
    instruction: "Rewrite to express that this is an obligation, using 〜なければなりません.",
    targetLabel: "〜なければならない",
    accepted: ["この書類[しょるい]にサインしなければなりません。", "この書類[しょるい]にサインしなければいけません。"],
    translationEn: "I have to sign this document.",
  },
  {
    id: "n4.nakereba-naranai.ex11",
    grammarPointId: "n4.nakereba-naranai",
    source: "bank",
    kind: "transformation",
    sourceJa: "毎日[まいにち]運動[うんどう]しなければなりません。",
    instruction: "Rewrite using the casual なきゃ contraction.",
    targetLabel: "なきゃ",
    accepted: ["毎日[まいにち]運動[うんどう]しなきゃ。", "毎日[まいにち]運動[うんどう]しなきゃいけない。"],
    translationEn: "I have to exercise every day.",
  },

  // -------------------------------------------------------------------
  // n4.temo-ii
  // -------------------------------------------------------------------
  {
    id: "n4.temo-ii.ex8",
    grammarPointId: "n4.temo-ii",
    source: "bank",
    kind: "mcq",
    question: "疲[つか]れたので、少[すこ]し＿＿。",
    choices: ["休[やす]んでください", "休[やす]んではいけません", "休[やす]まなければなりません", "休[やす]んでもいいですか"],
    correctIndex: 3,
    explanation: "Asking permission to rest a little uses 〜てもいいですか (休んでもいいですか).",
  },
  {
    id: "n4.temo-ii.ex9",
    grammarPointId: "n4.temo-ii",
    source: "bank",
    kind: "ordering",
    segments: ["この", "教科書[きょうかしょ]を", "借[か]りても", "いいですか。"],
    starIndex: 2,
    translationEn: "May I borrow this textbook?",
  },
  {
    id: "n4.temo-ii.ex10",
    grammarPointId: "n4.temo-ii",
    source: "bank",
    kind: "transformation",
    sourceJa: "この部屋[へや]でスマホを使[つか]います。",
    instruction: "Rewrite to prohibit this action using 〜てはいけません.",
    targetLabel: "〜てはいけない",
    accepted: ["この部屋[へや]でスマホを使[つか]ってはいけません。", "この部屋[へや]でスマホを使[つか]ってはだめです。"],
    translationEn: "You must not use your smartphone in this room.",
  },
  {
    id: "n4.temo-ii.ex11",
    grammarPointId: "n4.temo-ii",
    source: "bank",
    kind: "transformation",
    sourceJa: "会議室[かいぎしつ]でお茶[ちゃ]を飲[の]みます。",
    instruction: "Rewrite as a question asking for permission using 〜てもいいですか.",
    targetLabel: "〜てもいい",
    accepted: ["会議室[かいぎしつ]でお茶[ちゃ]を飲[の]んでもいいですか。", "会議室[かいぎしつ]でお茶[ちゃ]を飲[の]んでもいいでしょうか。"],
    translationEn: "May I drink tea in the meeting room?",
  },

  // -------------------------------------------------------------------
  // n4.age-kure-morau
  // -------------------------------------------------------------------
  {
    id: "n4.age-kure-morau.ex8",
    grammarPointId: "n4.age-kure-morau",
    source: "bank",
    kind: "mcq",
    question: "私[わたし]は近所[きんじょ]の子供[こども]にお菓子[かし]を＿＿。",
    choices: ["あげました", "くれました", "もらいました", "くださいました"],
    correctIndex: 0,
    explanation: "The speaker is the giver and the neighborhood children are the receivers (outward direction), so あげました is correct.",
  },
  {
    id: "n4.age-kure-morau.ex9",
    grammarPointId: "n4.age-kure-morau",
    source: "bank",
    kind: "ordering",
    segments: ["私[わたし]は", "友達[ともだち]に", "写真[しゃしん]を撮[と]って", "あげました。"],
    starIndex: 2,
    translationEn: "I took a photo for my friend (as a favor).",
  },
  {
    id: "n4.age-kure-morau.ex10",
    grammarPointId: "n4.age-kure-morau",
    source: "bank",
    kind: "transformation",
    sourceJa: "隣[となり]の人[ひと]は私[わたし]のパソコンを直[なお]してくれました。",
    instruction: "Rewrite from the receiver's perspective using もらう.",
    targetLabel: "もらう",
    accepted: ["私[わたし]は隣[となり]の人[ひと]にパソコンを直[なお]してもらいました。"],
    translationEn: "I had my neighbor fix my computer.",
  },
  {
    id: "n4.age-kure-morau.ex11",
    grammarPointId: "n4.age-kure-morau",
    source: "bank",
    kind: "transformation",
    sourceJa: "私[わたし]は同僚[どうりょう]に資料[しりょう]を作[つく]ってもらいました。",
    instruction: "Rewrite using くれる instead of もらう, from the giver's perspective.",
    targetLabel: "くれる",
    accepted: ["同僚[どうりょう]は私[わたし]に資料[しりょう]を作[つく]ってくれました。"],
    translationEn: "My colleague made the materials for me.",
  },

  // -------------------------------------------------------------------
  // n4.sou-da
  // -------------------------------------------------------------------
  {
    id: "n4.sou-da.ex8",
    grammarPointId: "n4.sou-da",
    source: "bank",
    kind: "mcq",
    question: "この店[みせ]のラーメンは＿＿です。",
    choices: ["いいそう", "よさそう", "いそう", "よいそう"],
    correctIndex: 1,
    explanation: "いい's appearance-そう form is the irregular よさそう, never ×いいそう or ×よいそう.",
  },
  {
    id: "n4.sou-da.ex9",
    grammarPointId: "n4.sou-da",
    source: "bank",
    kind: "ordering",
    segments: ["あの犬[いぬ]は", "今[いま]にも", "噛[か]み", "そうです。"],
    starIndex: 2,
    translationEn: "That dog looks like it's about to bite at any moment.",
  },
  {
    id: "n4.sou-da.ex10",
    grammarPointId: "n4.sou-da",
    source: "bank",
    kind: "transformation",
    sourceJa: "この橋[はし]は危[あぶ]ないです。",
    instruction: "Rewrite to express a guess based on appearance, using appearance-そう.",
    targetLabel: "様態のそう",
    accepted: ["この橋[はし]は危[あぶ]なそうです。"],
    translationEn: "This bridge looks dangerous.",
  },
  {
    id: "n4.sou-da.ex11",
    grammarPointId: "n4.sou-da",
    source: "bank",
    kind: "transformation",
    sourceJa: "そのおもちゃは壊[こわ]れます。",
    instruction: "Rewrite to express that it looks like it's about to happen, using verb-stem + そう.",
    targetLabel: "様態のそう",
    accepted: ["そのおもちゃは壊[こわ]れそうです。"],
    translationEn: "That toy looks like it's about to break.",
  },

  // -------------------------------------------------------------------
  // n4.you-ni-naru
  // -------------------------------------------------------------------
  {
    id: "n4.you-ni-naru.ex8",
    grammarPointId: "n4.you-ni-naru",
    source: "bank",
    kind: "mcq",
    question: "運動[うんどう]して、体[からだ]が＿＿。",
    choices: ["元気[げんき]するようになりました", "元気[げんき]になるようになりました", "元気[げんき]になりました", "元気[げんき]ようになりました"],
    correctIndex: 2,
    explanation: "な-adjectives attach directly to なる (元気になる), not ようになる, which is reserved for verbs.",
  },
  {
    id: "n4.you-ni-naru.ex9",
    grammarPointId: "n4.you-ni-naru",
    source: "bank",
    kind: "ordering",
    segments: ["毎日[まいにち]練習[れんしゅう]して、", "漢字[かんじ]が", "上手[じょうず]に", "書[か]けるようになりました。"],
    starIndex: 2,
    translationEn: "I practiced every day, and I've become able to write kanji well.",
  },
  {
    id: "n4.you-ni-naru.ex10",
    grammarPointId: "n4.you-ni-naru",
    source: "bank",
    kind: "transformation",
    sourceJa: "妹[いもうと]は自転車[じてんしゃ]に乗[の]れます。",
    instruction: "Rewrite to show this is a newly acquired ability, using 〜ようになりました.",
    targetLabel: "〜ようになる",
    accepted: ["妹[いもうと]は自転車[じてんしゃ]に乗[の]れるようになりました。"],
    translationEn: "My younger sister has become able to ride a bicycle.",
  },
  {
    id: "n4.you-ni-naru.ex11",
    grammarPointId: "n4.you-ni-naru",
    source: "bank",
    kind: "transformation",
    sourceJa: "彼[かれ]はたばこを吸[す]います。",
    instruction: "Rewrite to show he no longer does this, using 〜なくなりました.",
    targetLabel: "〜なくなる",
    accepted: ["彼[かれ]はたばこを吸[す]わなくなりました。"],
    translationEn: "He no longer smokes (he used to, but doesn't anymore).",
  },
];
