// Batch 2 exercises for the N5 sentence-pattern points (ex8–ex11).
// Sidecar to grammar/n5/batch1-patterns.ts — see CONTENT_GUIDE.md "Sidecar files".

import type { Exercise } from "../../types";

export const exercises: Exercise[] = [
  // ---- n5.ga-hoshii ------------------------------------------------------
  {
    id: "n5.ga-hoshii.ex8",
    grammarPointId: "n5.ga-hoshii",
    source: "bank",
    kind: "mcq",
    question: "母[はは]は新[あたら]しい掃除機[そうじき]を＿＿。",
    choices: ["ほしいです", "ほしがっています", "ほしくないです", "ほしかったです"],
    correctIndex: 1,
    explanation:
      "The particle を tells us this is about someone else's want, which needs ほしがっている. Plain ほしい pairs with が and is for the speaker's own feelings.",
  },
  {
    id: "n5.ga-hoshii.ex9",
    grammarPointId: "n5.ga-hoshii",
    source: "bank",
    kind: "ordering",
    segments: ["母[はは]の日[ひ]に、", "赤[あか]い", "花[はな]が", "ほしいです。"],
    starIndex: 2,
    translationEn: "For Mother's Day, I want red flowers.",
  },
  {
    id: "n5.ga-hoshii.ex10",
    grammarPointId: "n5.ga-hoshii",
    source: "bank",
    kind: "transformation",
    sourceJa: "新[あたら]しい辞書[じしょ]を買[か]います。",
    instruction: "Rewrite as a statement that you want the dictionary, using 〜がほしい.",
    targetLabel: "〜がほしい",
    accepted: ["新[あたら]しい辞書[じしょ]がほしいです。", "新[あたら]しい辞書[じしょ]がほしい。"],
    translationEn: "I want a new dictionary.",
  },
  {
    id: "n5.ga-hoshii.ex11",
    grammarPointId: "n5.ga-hoshii",
    source: "bank",
    kind: "transformation",
    sourceJa: "弟[おとうと]は新[あたら]しいゲームがほしいです。",
    instruction:
      "Rewrite describing the brother's want from an outside (third-person) view, using ほしがっている. Watch the particle.",
    targetLabel: "ほしがっている",
    accepted: [
      "弟[おとうと]は新[あたら]しいゲームをほしがっています。",
      "弟[おとうと]は新[あたら]しいゲームをほしがっている。",
    ],
    translationEn: "My younger brother wants a new game.",
  },

  // ---- n5.no-ga-suki ------------------------------------------------------
  {
    id: "n5.no-ga-suki.ex8",
    grammarPointId: "n5.no-ga-suki",
    source: "bank",
    kind: "mcq",
    question: "兄[あに]は絵[え]をかくの＿＿上手[じょうず]です。",
    choices: ["を", "に", "が", "と"],
    correctIndex: 2,
    explanation:
      "好き/上手/下手 are adjectives, so the nominalized verb clause is marked with が, not を/に/と.",
  },
  {
    id: "n5.no-ga-suki.ex9",
    grammarPointId: "n5.no-ga-suki",
    source: "bank",
    kind: "ordering",
    segments: ["彼[かれ]は", "魚[さかな]を", "釣[つ]るのが", "好[す]きです。"],
    starIndex: 2,
    translationEn: "He likes fishing.",
  },
  {
    id: "n5.no-ga-suki.ex10",
    grammarPointId: "n5.no-ga-suki",
    source: "bank",
    kind: "transformation",
    sourceJa: "毎朝[まいあさ]公園[こうえん]を走[はし]ります。",
    instruction: "Rewrite as a statement that you like doing this, using 〜のが好きです.",
    targetLabel: "〜のが好き",
    accepted: [
      "毎朝[まいあさ]公園[こうえん]を走[はし]るのが好[す]きです。",
      "私[わたし]は毎朝[まいあさ]公園[こうえん]を走[はし]るのが好[す]きです。",
    ],
    translationEn: "I like running in the park every morning.",
  },
  {
    id: "n5.no-ga-suki.ex11",
    grammarPointId: "n5.no-ga-suki",
    source: "bank",
    kind: "transformation",
    sourceJa: "私[わたし]はケーキを作[つく]るのが上手[じょうず]です。",
    instruction:
      "Praising your own skill with 上手 sounds boastful — rewrite using 得意 instead.",
    targetLabel: "得意",
    accepted: [
      "私[わたし]はケーキを作[つく]るのが得意[とくい]です。",
      "私[わたし]はケーキを作[つく]るのが得意[とくい]だ。",
    ],
    translationEn: "I'm good at making cake (said modestly of myself).",
  },

  // ---- n5.kara-reason ------------------------------------------------------
  {
    id: "n5.kara-reason.ex8",
    grammarPointId: "n5.kara-reason",
    source: "bank",
    kind: "mcq",
    question: "疲[つか]れました＿＿、早[はや]く寝[ね]ます。",
    choices: ["でも", "のに", "を", "から"],
    correctIndex: 3,
    explanation:
      "から attaches the reason (being tired) to the result (going to bed early). でも doesn't connect clauses this way, のに would flip the logic to \"even though,\" and を is an object particle.",
  },
  {
    id: "n5.kara-reason.ex9",
    grammarPointId: "n5.kara-reason",
    source: "bank",
    kind: "ordering",
    segments: ["頭[あたま]が", "痛[いた]いから、", "今日[きょう]は", "早[はや]く帰[かえ]ります。"],
    starIndex: 1,
    translationEn: "I have a headache, so I'm going home early today.",
  },
  {
    id: "n5.kara-reason.ex10",
    grammarPointId: "n5.kara-reason",
    source: "bank",
    kind: "transformation",
    sourceJa: "熱[ねつ]があります。学校[がっこう]を休[やす]みます。",
    instruction: "Combine these two sentences into one, using 〜から to state the reason.",
    targetLabel: "〜から",
    accepted: [
      "熱[ねつ]がありますから、学校[がっこう]を休[やす]みます。",
      "熱[ねつ]があるから、学校[がっこう]を休[やす]みます。",
    ],
    translationEn: "I have a fever, so I'll stay home from school.",
  },
  {
    id: "n5.kara-reason.ex11",
    grammarPointId: "n5.kara-reason",
    source: "bank",
    kind: "transformation",
    sourceJa: "エアコンがこわれていますから、部屋[へや]が暑[あつ]いです。",
    instruction: "Rewrite as a short answer to どうして部屋が暑いですか, using 〜からです.",
    targetLabel: "〜からです",
    accepted: ["エアコンがこわれているからです。", "エアコンがこわれているからだ。"],
    translationEn: "Because the air conditioner is broken.",
  },

  // ---- n5.mae-ni-ato-de ------------------------------------------------------
  {
    id: "n5.mae-ni-ato-de.ex8",
    grammarPointId: "n5.mae-ni-ato-de",
    source: "bank",
    kind: "mcq",
    question: "食事[しょくじ]＿＿前[まえ]に、手[て]を洗[あら]います。",
    choices: ["の", "を", "が", "に"],
    correctIndex: 0,
    explanation: "Nouns connect to 前に/後で with の, not another particle: 食事の前に.",
  },
  {
    id: "n5.mae-ni-ato-de.ex9",
    grammarPointId: "n5.mae-ni-ato-de",
    source: "bank",
    kind: "ordering",
    segments: ["テストが", "始[はじ]まる前[まえ]に、", "名前[なまえ]を", "書[か]いてください。"],
    starIndex: 1,
    translationEn: "Please write your name before the test begins.",
  },
  {
    id: "n5.mae-ni-ato-de.ex10",
    grammarPointId: "n5.mae-ni-ato-de",
    source: "bank",
    kind: "transformation",
    sourceJa: "宿題[しゅくだい]をします。そして、テレビを見[み]ます。",
    instruction: "Combine into one sentence using 〜前に, with watching TV as the reference point.",
    targetLabel: "前に",
    accepted: [
      "テレビを見[み]る前[まえ]に、宿題[しゅくだい]をします。",
      "テレビを見[み]る前[まえ]に、宿題[しゅくだい]をする。",
    ],
    translationEn: "Before watching TV, I do my homework.",
  },
  {
    id: "n5.mae-ni-ato-de.ex11",
    grammarPointId: "n5.mae-ni-ato-de",
    source: "bank",
    kind: "transformation",
    sourceJa: "顔[かお]を洗[あら]います。そして、朝[あさ]ごはんを食[た]べます。",
    instruction: "Combine into one sentence using 〜た後で.",
    targetLabel: "た後で",
    accepted: [
      "顔[かお]を洗[あら]った後[あと]で、朝[あさ]ごはんを食[た]べます。",
      "顔[かお]を洗[あら]った後[あと]で、朝[あさ]ごはんを食[た]べる。",
    ],
    translationEn: "After washing my face, I eat breakfast.",
  },

  // ---- n5.mou-mada ------------------------------------------------------
  {
    id: "n5.mou-mada.ex8",
    grammarPointId: "n5.mou-mada",
    source: "bank",
    kind: "mcq",
    question: "祖父[そふ]は80歳[さい]ですが、＿＿元気[げんき]です。",
    choices: ["もう", "まだ", "ぜんぜん", "いつも"],
    correctIndex: 1,
    explanation:
      "まだ + affirmative = \"still\": despite being 80, my grandfather is still healthy. もう + affirmative doesn't mean \"still,\" ぜんぜん needs a negative, and いつも means \"always.\"",
  },
  {
    id: "n5.mou-mada.ex9",
    grammarPointId: "n5.mou-mada",
    source: "bank",
    kind: "ordering",
    segments: ["父[ちち]は", "まだ", "会社[かいしゃ]から", "帰[かえ]っていません。"],
    starIndex: 1,
    translationEn: "My father hasn't come home from work yet.",
  },
  {
    id: "n5.mou-mada.ex10",
    grammarPointId: "n5.mou-mada",
    source: "bank",
    kind: "transformation",
    sourceJa: "妹[いもうと]はもう宿題[しゅくだい]をしました。",
    instruction: "Rewrite as the negative \"not yet\" — assume she hasn't done it.",
    targetLabel: "まだ〜ていません",
    accepted: [
      "妹[いもうと]はまだ宿題[しゅくだい]をしていません。",
      "妹[いもうと]はまだ宿題[しゅくだい]をしていない。",
    ],
    translationEn: "My sister hasn't done her homework yet.",
  },
  {
    id: "n5.mou-mada.ex11",
    grammarPointId: "n5.mou-mada",
    source: "bank",
    kind: "transformation",
    sourceJa: "私[わたし]はまだ晩[ばん]ごはんの準備[じゅんび]をしていません。",
    instruction: "Rewrite as the affirmative \"already\" — assume you have finished.",
    targetLabel: "もう〜ました",
    accepted: [
      "私[わたし]はもう晩[ばん]ごはんの準備[じゅんび]をしました。",
      "私[わたし]はもう晩[ばん]ごはんの準備[じゅんび]をした。",
    ],
    translationEn: "I have already prepared dinner.",
  },

  // ---- n5.naru ------------------------------------------------------
  {
    id: "n5.naru.ex8",
    grammarPointId: "n5.naru",
    source: "bank",
    kind: "mcq",
    question: "薬[くすり]を飲[の]んだら、少[すこ]し＿＿なりました。",
    choices: ["元気[げんき]な", "元気[げんき]", "元気[げんき]に", "元気[げんき]の"],
    correctIndex: 2,
    explanation:
      "な-adjectives drop な and take に before なる: 元気になる. The plain form, bare な, and の cannot attach to なる directly.",
  },
  {
    id: "n5.naru.ex9",
    grammarPointId: "n5.naru",
    source: "bank",
    kind: "ordering",
    segments: ["毎日[まいにち]野菜[やさい]を食[た]べて、", "体[からだ]が", "丈夫[じょうぶ]に", "なりました。"],
    starIndex: 2,
    translationEn: "I ate vegetables every day, and my body became strong.",
  },
  {
    id: "n5.naru.ex10",
    grammarPointId: "n5.naru",
    source: "bank",
    kind: "transformation",
    sourceJa: "この道[みち]は狭[せま]いです。",
    instruction: "Rewrite to say the road GOT narrow (a change happened), using 〜くなる.",
    targetLabel: "〜くなる",
    accepted: ["この道[みち]は狭[せま]くなりました。", "この道[みち]は狭[せま]くなった。"],
    translationEn: "This road has gotten narrow.",
  },
  {
    id: "n5.naru.ex11",
    grammarPointId: "n5.naru",
    source: "bank",
    kind: "transformation",
    sourceJa: "彼女[かのじょ]は有名[ゆうめい]です。",
    instruction: "Rewrite to say she BECAME famous, using 〜になる.",
    targetLabel: "〜になる",
    accepted: ["彼女[かのじょ]は有名[ゆうめい]になりました。", "彼女[かのじょ]は有名[ゆうめい]になった。"],
    translationEn: "She became famous.",
  },
];
