// Batch 2 exercises for the N5 seed points (ex8–ex11).
// Sidecar to grammar/n5/seed.ts — see CONTENT_GUIDE.md "Sidecar files".

import type { Exercise } from "../../types";

export const exercises: Exercise[] = [
  // -------------------------------------------------------------------
  // n5.wa-ga (particle point — escape hatch: 1 transformation + 1 extra cloze)
  // -------------------------------------------------------------------
  {
    id: "n5.wa-ga.ex8",
    grammarPointId: "n5.wa-ga",
    source: "bank",
    kind: "mcq",
    question: "クラスで誰[だれ]＿＿一番[いちばん]背[せ]が高[たか]いですか。",
    choices: ["を", "は", "が", "も"],
    correctIndex: 2,
    explanation: "誰 (who) is the grammatical subject of 高い here, and question words as subject always take が, never は/を/も.",
  },
  {
    id: "n5.wa-ga.ex9",
    grammarPointId: "n5.wa-ga",
    source: "bank",
    kind: "ordering",
    segments: ["この", "店[みせ]は", "魚[さかな]が", "新鮮[しんせん]です。"],
    starIndex: 2,
    translationEn: "This store's fish is fresh.",
  },
  {
    id: "n5.wa-ga.ex10",
    grammarPointId: "n5.wa-ga",
    source: "bank",
    kind: "transformation",
    sourceJa: "この医者[いしゃ]は田中[たなか]さんです。",
    instruction: "Rewrite to identify who the doctor is, marking the person with が instead of は.",
    targetLabel: "が",
    accepted: ["田中[たなか]さんがこの医者[いしゃ]です。", "田中[たなか]さんがこの医者[いしゃ]だ。"],
    translationEn: "Mr. Tanaka is the doctor.",
  },
  {
    id: "n5.wa-ga.ex11",
    grammarPointId: "n5.wa-ga",
    source: "bank",
    kind: "cloze",
    sentence: "この店[みせ]＿＿ラーメンがおいしいです。",
    accepted: ["は"],
    translationEn: "As for this shop, the ramen is delicious.",
  },

  // -------------------------------------------------------------------
  // n5.o-ni-de (particle point — escape hatch: 1 transformation + 1 extra cloze)
  // -------------------------------------------------------------------
  {
    id: "n5.o-ni-de.ex8",
    grammarPointId: "n5.o-ni-de",
    source: "bank",
    kind: "mcq",
    question: "毎朝[まいあさ]公園[こうえん]＿＿散歩[さんぽ]します。",
    choices: ["を", "に", "へ", "で"],
    correctIndex: 3,
    explanation: "散歩します is an action, so its location takes で, not に (existence) or へ/を.",
  },
  {
    id: "n5.o-ni-de.ex9",
    grammarPointId: "n5.o-ni-de",
    source: "bank",
    kind: "ordering",
    segments: ["母[はは]は", "スーパーで", "野菜[やさい]を", "買[か]います。"],
    starIndex: 2,
    translationEn: "Mom buys vegetables at the supermarket.",
  },
  {
    id: "n5.o-ni-de.ex10",
    grammarPointId: "n5.o-ni-de",
    source: "bank",
    kind: "transformation",
    sourceJa: "父[ちち]は今[いま]台所[だいどころ]にいます。",
    instruction: "Rewrite to say he is cooking there now, changing に (existence) to で (location of an action).",
    targetLabel: "で",
    accepted: ["父[ちち]は今[いま]台所[だいどころ]で料理[りょうり]をしています。", "父[ちち]は今[いま]台所[だいどころ]で料理[りょうり]をしている。"],
    translationEn: "Dad is cooking in the kitchen now.",
  },
  {
    id: "n5.o-ni-de.ex11",
    grammarPointId: "n5.o-ni-de",
    source: "bank",
    kind: "cloze",
    sentence: "妹[いもうと]は九時[くじ]＿＿寝[ね]ます。",
    accepted: ["に"],
    translationEn: "My little sister goes to bed at nine o'clock.",
  },

  // -------------------------------------------------------------------
  // n5.masu-form
  // -------------------------------------------------------------------
  {
    id: "n5.masu-form.ex8",
    grammarPointId: "n5.masu-form",
    source: "bank",
    kind: "mcq",
    question: "先週[せんしゅう]、京都[きょうと]へ＿＿。",
    choices: ["行[い]きます", "行[い]きました", "行[い]きません", "行[い]きませんでした"],
    correctIndex: 1,
    explanation: "先週 (last week) marks a completed past action, so the polite past 行きました is required.",
  },
  {
    id: "n5.masu-form.ex9",
    grammarPointId: "n5.masu-form",
    source: "bank",
    kind: "ordering",
    segments: ["姉[あね]は", "先週[せんしゅう]", "大阪[おおさか]へ", "行[い]きました。"],
    starIndex: 2,
    translationEn: "My older sister went to Osaka last week.",
  },
  {
    id: "n5.masu-form.ex10",
    grammarPointId: "n5.masu-form",
    source: "bank",
    kind: "transformation",
    sourceJa: "友達[ともだち]に手紙[てがみ]を書[か]きます。",
    instruction: "Rewrite in the polite past tense (〜ました).",
    targetLabel: "ました形",
    accepted: ["友達[ともだち]に手紙[てがみ]を書[か]きました。"],
    translationEn: "I wrote a letter to my friend.",
  },
  {
    id: "n5.masu-form.ex11",
    grammarPointId: "n5.masu-form",
    source: "bank",
    kind: "transformation",
    sourceJa: "毎晩[まいばん]お風呂[ふろ]に入[はい]ります。",
    instruction: "Rewrite in the negative (〜ません).",
    targetLabel: "ません形",
    accepted: ["毎晩[まいばん]お風呂[ふろ]に入[はい]りません。"],
    translationEn: "I don't take a bath every night.",
  },

  // -------------------------------------------------------------------
  // n5.te-form
  // -------------------------------------------------------------------
  {
    id: "n5.te-form.ex8",
    grammarPointId: "n5.te-form",
    source: "bank",
    kind: "mcq",
    question: "友達[ともだち]と電話[でんわ]で＿＿、宿題[しゅくだい]をしました。",
    choices: ["話[はな]して", "話[はな]んで", "話[はな]いて", "話[はな]って"],
    correctIndex: 0,
    explanation: "話す is a godan す-ending verb, which takes して in the て-form — not んで/いて/って, which belong to ぬ/ぶ/む-, く/ぐ-, or う/つ/る-ending verbs.",
  },
  {
    id: "n5.te-form.ex9",
    grammarPointId: "n5.te-form",
    source: "bank",
    kind: "ordering",
    segments: ["スーパーへ", "行[い]って", "牛乳[ぎゅうにゅう]を", "買[か]いました。"],
    starIndex: 1,
    translationEn: "I went to the supermarket and bought milk.",
  },
  {
    id: "n5.te-form.ex10",
    grammarPointId: "n5.te-form",
    source: "bank",
    kind: "transformation",
    sourceJa: "電気[でんき]を消[け]します。",
    instruction: "Rewrite as a polite request using 〜てください.",
    targetLabel: "てください",
    accepted: ["電気[でんき]を消[け]してください。"],
    translationEn: "Please turn off the light.",
  },
  {
    id: "n5.te-form.ex11",
    grammarPointId: "n5.te-form",
    source: "bank",
    kind: "transformation",
    sourceJa: "子供[こども]たちが公園[こうえん]で遊[あそ]びます。",
    instruction: "Rewrite to describe the action in progress right now, using 〜ている.",
    targetLabel: "ている形",
    accepted: ["子供[こども]たちが公園[こうえん]で遊[あそ]んでいます。", "子供[こども]たちが公園[こうえん]で遊[あそ]んでいる。"],
    translationEn: "The children are playing in the park.",
  },

  // -------------------------------------------------------------------
  // n5.i-adjectives
  // -------------------------------------------------------------------
  {
    id: "n5.i-adjectives.ex8",
    grammarPointId: "n5.i-adjectives",
    source: "bank",
    kind: "mcq",
    question: "先月[せんげつ]は暑[あつ]かったですが、今月[こんげつ]は＿＿。",
    choices: ["暑[あつ]かったです", "暑[あつ]くなかったです", "暑[あつ]いです", "暑[あつ]くないです"],
    correctIndex: 3,
    explanation: "今月 (this month) is present, and the contrast implies negation, so the present negative 暑くないです is needed, not a past form.",
  },
  {
    id: "n5.i-adjectives.ex9",
    grammarPointId: "n5.i-adjectives",
    source: "bank",
    kind: "ordering",
    segments: ["この", "かばんは", "軽[かる]くて", "丈夫[じょうぶ]です。"],
    starIndex: 2,
    translationEn: "This bag is light and sturdy.",
  },
  {
    id: "n5.i-adjectives.ex10",
    grammarPointId: "n5.i-adjectives",
    source: "bank",
    kind: "transformation",
    sourceJa: "このラーメンは辛[から]いです。",
    instruction: "Rewrite in the negative form (〜くない), saying it is not spicy.",
    targetLabel: "くない形",
    accepted: ["このラーメンは辛[から]くないです。", "このラーメンは辛[から]くありません。"],
    translationEn: "This ramen is not spicy.",
  },
  {
    id: "n5.i-adjectives.ex11",
    grammarPointId: "n5.i-adjectives",
    source: "bank",
    kind: "transformation",
    sourceJa: "彼[かれ]のかばんは重[おも]いです。",
    instruction: "Rewrite in the past tense (〜かったです).",
    targetLabel: "かった形",
    accepted: ["彼[かれ]のかばんは重[おも]かったです。"],
    translationEn: "His bag was heavy.",
  },

  // -------------------------------------------------------------------
  // n5.na-adjectives
  // -------------------------------------------------------------------
  {
    id: "n5.na-adjectives.ex8",
    grammarPointId: "n5.na-adjectives",
    source: "bank",
    kind: "mcq",
    question: "去年[きょねん]、この町[まち]は＿＿。",
    choices: ["静[しず]かです", "静[しず]かでした", "静[しず]かじゃないです", "静[しず]かな"],
    correctIndex: 1,
    explanation: "去年 (last year) is past, so the copula must be past でした; the bare stem alone or な (used only before a noun) cannot stand as a predicate.",
  },
  {
    id: "n5.na-adjectives.ex9",
    grammarPointId: "n5.na-adjectives",
    source: "bank",
    kind: "ordering",
    segments: ["この", "仕事[しごと]は", "複雑[ふくざつ]で", "大変[たいへん]です。"],
    starIndex: 2,
    translationEn: "This job is complicated and difficult.",
  },
  {
    id: "n5.na-adjectives.ex10",
    grammarPointId: "n5.na-adjectives",
    source: "bank",
    kind: "transformation",
    sourceJa: "この道[みち]は安全[あんぜん]です。",
    instruction: "Rewrite in the negative (〜じゃない), saying it is not safe.",
    targetLabel: "じゃない形",
    accepted: ["この道[みち]は安全[あんぜん]じゃないです。", "この道[みち]は安全[あんぜん]ではありません。"],
    translationEn: "This road is not safe.",
  },
  {
    id: "n5.na-adjectives.ex11",
    grammarPointId: "n5.na-adjectives",
    source: "bank",
    kind: "transformation",
    sourceJa: "田中[たなか]さんは親切[しんせつ]です。",
    instruction: "Rewrite as one sentence saying 'Mr. Tanaka is a kind person,' attaching な before 人[ひと].",
    targetLabel: "な形",
    accepted: ["田中[たなか]さんは親切[しんせつ]な人[ひと]です。"],
    translationEn: "Mr. Tanaka is a kind person.",
  },

  // -------------------------------------------------------------------
  // n5.tai-form
  // -------------------------------------------------------------------
  {
    id: "n5.tai-form.ex8",
    grammarPointId: "n5.tai-form",
    source: "bank",
    kind: "mcq",
    question: "お腹[なか]がいっぱいですから、もう＿＿。",
    choices: ["食[た]べたいです", "食[た]べたかったです", "食[た]べたくないです", "食[た]べたくなかったです"],
    correctIndex: 2,
    explanation: "お腹がいっぱい (being full) describes a present negative desire, so 食べたくないです is correct — not a past form.",
  },
  {
    id: "n5.tai-form.ex9",
    grammarPointId: "n5.tai-form",
    source: "bank",
    kind: "ordering",
    segments: ["今度[こんど]の", "休[やす]みに", "海[うみ]に", "行[い]きたいです。"],
    starIndex: 2,
    translationEn: "I want to go to the sea on my next day off.",
  },
  {
    id: "n5.tai-form.ex10",
    grammarPointId: "n5.tai-form",
    source: "bank",
    kind: "transformation",
    sourceJa: "新[あたら]しい携帯[けいたい]を買[か]いたいです。",
    instruction: "Rewrite in the negative (〜たくない), saying you don't want to buy it.",
    targetLabel: "たくない形",
    accepted: ["新[あたら]しい携帯[けいたい]を買[か]いたくないです。", "新[あたら]しい携帯[けいたい]を買[か]いたくない。"],
    translationEn: "I don't want to buy a new phone.",
  },
  {
    id: "n5.tai-form.ex11",
    grammarPointId: "n5.tai-form",
    source: "bank",
    kind: "transformation",
    sourceJa: "有名[ゆうめい]な歌手[かしゅ]になりたいです。",
    instruction: "Rewrite in the past tense (〜たかったです).",
    targetLabel: "たかった形",
    accepted: ["有名[ゆうめい]な歌手[かしゅ]になりたかったです。"],
    translationEn: "I wanted to become a famous singer.",
  },

  // -------------------------------------------------------------------
  // n5.aru-iru
  // -------------------------------------------------------------------
  {
    id: "n5.aru-iru.ex8",
    grammarPointId: "n5.aru-iru",
    source: "bank",
    kind: "mcq",
    question: "冷蔵庫[れいぞうこ]の中[なか]に何[なに]も＿＿。",
    choices: ["ありません", "いません", "ない", "いない"],
    correctIndex: 0,
    explanation: "何も (nothing) here refers to inanimate items in the fridge, so the negative existence verb is ありません, not いません, which is for people/animals.",
  },
  {
    id: "n5.aru-iru.ex9",
    grammarPointId: "n5.aru-iru",
    source: "bank",
    kind: "ordering",
    segments: ["テーブルの", "上[うえ]に", "果物[くだもの]が", "あります。"],
    starIndex: 2,
    translationEn: "There is a lot of fruit on the table.",
  },
  {
    id: "n5.aru-iru.ex10",
    grammarPointId: "n5.aru-iru",
    source: "bank",
    kind: "transformation",
    sourceJa: "庭[にわ]に鳥[とり]がいます。",
    instruction: "Rewrite in the negative (いません), saying there is no bird there.",
    targetLabel: "いません",
    accepted: ["庭[にわ]に鳥[とり]がいません。"],
    translationEn: "There is no bird in the garden.",
  },
  {
    id: "n5.aru-iru.ex11",
    grammarPointId: "n5.aru-iru",
    source: "bank",
    kind: "transformation",
    sourceJa: "机[つくえ]の上[うえ]に鍵[かぎ]があります。",
    instruction: "Rewrite to say where the (already-known) key is, making 鍵 the topic with は instead of が.",
    targetLabel: "は",
    accepted: ["鍵[かぎ]は机[つくえ]の上[うえ]にあります。"],
    translationEn: "The key is on the desk.",
  },
];
