// Particle drill items (助詞). Authored fresh rather than mined from cloze
// exercises — cloze `accepted` is arbitrary text, so filtering it for
// particle-shaped answers would be fragile.

import type { ParticleDrillItem } from "../types";

/** The choice set a particle question draws its distractors from by default. */
export const PARTICLE_SET = [
  "は",
  "が",
  "を",
  "に",
  "で",
  "へ",
  "と",
  "も",
  "から",
  "まで",
  "より",
  "の",
] as const;

export const allParticleItems: ParticleDrillItem[] = [
  // ---------------------------------------------------------------------
  // は vs が (topic vs subject, new vs known information)
  // ---------------------------------------------------------------------
  {
    id: "pd.wa-self-intro",
    sentence: "わたし＿＿田中[たなか]です。",
    answer: "は",
    distractors: ["が", "を", "に"],
    translationEn: "I am Tanaka.",
    level: "N5",
    note: "は marks わたし as the topic being introduced; が would sound like answering 'who is Tanaka?' instead, and を/に don't fit a simple X is Y sentence.",
  },
  {
    id: "pd.ga-question-word",
    sentence: "だれ＿＿来[き]ましたか。",
    answer: "が",
    distractors: ["は", "を", "で"],
    translationEn: "Who came?",
    level: "N5",
    note: "Question words like だれ/なに/どこ asking for new information take が; は cannot mark an unknown item as topic.",
  },
  {
    id: "pd.ga-suki",
    sentence: "わたしは日本料理[にほんりょうり]＿＿好[す]きです。",
    answer: "が",
    distractors: ["は", "を", "に"],
    translationEn: "I like Japanese food.",
    level: "N5",
    note: "好き takes が for what is liked, even though わたし is already the sentence topic (marked by は); を is wrong because 好き is an adjective, not an action verb.",
  },
  {
    id: "pd.ga-jouzu",
    sentence: "田中[たなか]さんはピアノ＿＿上手[じょうず]です。",
    answer: "が",
    distractors: ["は", "を", "に"],
    translationEn: "Tanaka is good at piano.",
    level: "N4",
    note: "上手 is an adjective describing skill, so what the skill is about takes が, not を.",
  },
  {
    id: "pd.ga-hoshii",
    sentence: "新[あたら]しいパソコン＿＿ほしいです。",
    answer: "が",
    distractors: ["は", "を", "に"],
    translationEn: "I want a new computer.",
    level: "N4",
    note: "ほしい is an adjective of desire, so the thing wanted takes が, not を like a verb's direct object.",
  },
  {
    id: "pd.wa-contrast",
    sentence: "肉[にく]＿＿食[た]べますが、魚[さかな]は食[た]べません。",
    answer: "は",
    distractors: ["が", "に", "で"],
    translationEn: "I eat meat, but I don't eat fish.",
    level: "N4",
    note: "は sets up a contrast with 魚は in the second clause; が cannot mark the direct object of 食べる at all.",
  },
  {
    id: "pd.wa-known-topic",
    sentence: "この店[みせ]＿＿安[やす]くておいしいです。",
    answer: "は",
    distractors: ["が", "で", "に"],
    translationEn: "This restaurant is cheap and delicious.",
    level: "N5",
    note: "は presents この店 as the topic being commented on; が would instead answer an implied 'which restaurant is cheap?'",
  },
  {
    id: "pd.ga-existence-aru",
    sentence: "机[つくえ]の上[うえ]に本[ほん]＿＿あります。",
    answer: "が",
    distractors: ["は", "に", "を"],
    translationEn: "There is a book on the desk.",
    level: "N5",
    note: "が marks the subject of あります when introducing what exists; は would imply the book was already under discussion.",
  },
  {
    id: "pd.ga-answer-focus",
    sentence: "A:「だれが窓[まど]を開[あ]けましたか。」B:「山田[やまだ]さん＿＿開[あ]けました。」",
    answer: "が",
    distractors: ["は", "を", "に"],
    translationEn: 'A: "Who opened the window?" B: "Yamada did."',
    level: "N4",
    note: "Answering a が-question with who did it also takes が, not は, to directly supply the new information asked for.",
  },
  {
    id: "pd.wa-general-truth",
    sentence: "地球[ちきゅう]＿＿丸[まる]いです。",
    answer: "は",
    distractors: ["が", "を", "に"],
    translationEn: "The Earth is round.",
    level: "N5",
    note: "は marks a general statement about a known topic; が would instead answer an implied 'what is round?'",
  },

  // ---------------------------------------------------------------------
  // に vs で (destination/point-in-time vs location of action)
  // ---------------------------------------------------------------------
  {
    id: "pd.ni-destination",
    sentence: "明日[あした]、大阪[おおさか]＿＿行[い]きます。",
    answer: "に",
    distractors: ["で", "を", "が"],
    translationEn: "Tomorrow I will go to Osaka.",
    level: "N5",
    note: "に marks the destination of 行く; で would mark where an action takes place, not where one is headed.",
  },
  {
    id: "pd.de-location-action",
    sentence: "図書館[としょかん]＿＿勉強[べんきょう]します。",
    answer: "で",
    distractors: ["に", "を", "へ"],
    translationEn: "I study at the library.",
    level: "N5",
    note: "で marks the location where an action happens; に is for a destination or the location of existence (いる/ある), not where an activity takes place.",
  },
  {
    id: "pd.ni-sumu",
    sentence: "兄[あに]は東京[とうきょう]＿＿住[す]んでいます。",
    answer: "に",
    distractors: ["で", "を", "は"],
    translationEn: "My older brother lives in Tokyo.",
    level: "N4",
    note: "住む takes に for the place of residence, a state of being located; で marks where an action is performed, which doesn't fit living somewhere.",
  },
  {
    id: "pd.de-hataraku",
    sentence: "姉[あね]は銀行[ぎんこう]＿＿働[はたら]いています。",
    answer: "で",
    distractors: ["に", "を", "へ"],
    translationEn: "My older sister works at a bank.",
    level: "N4",
    note: "働く is an action verb, so the workplace takes で; に would treat the bank as a destination or existence-location instead of where the activity happens.",
  },
  {
    id: "pd.de-vs-ni-party",
    sentence: "土曜日[どようび]に公園[こうえん]＿＿パーティーをします。",
    answer: "で",
    distractors: ["に", "を", "へ"],
    translationEn: "On Saturday we will have a party in the park.",
    level: "N4",
    note: "で marks the venue where the party happens; に would make the park sound like a destination rather than the place the event occurs.",
  },
  {
    id: "pd.ni-time-point",
    sentence: "毎朝[まいあさ]七時[しちじ]＿＿起[お]きます。",
    answer: "に",
    distractors: ["で", "から", "が"],
    translationEn: "I get up at seven every morning.",
    level: "N5",
    note: "に marks a specific point in time for a momentary action; で marks location, and から would mark a starting point, not a single moment.",
  },
  {
    id: "pd.ni-indirect-object",
    sentence: "友達[ともだち]＿＿誕生日[たんじょうび]プレゼントをあげました。",
    answer: "に",
    distractors: ["と", "を", "から"],
    translationEn: "I gave my friend a birthday present.",
    level: "N5",
    note: "に marks the recipient of あげる; と would imply a mutual action rather than one-directional giving.",
  },
  {
    id: "pd.ni-passive-agent",
    sentence: "弟[おとうと]は母[はは]＿＿しかられました。",
    answer: "に",
    distractors: ["を", "で", "へ"],
    translationEn: "My younger brother was scolded by our mother.",
    level: "N4",
    note: "に marks the agent in a direct passive sentence; を would be wrong since the passive verb's grammatical subject is 弟, not 母.",
  },
  {
    id: "pd.ni-naru-result",
    sentence: "来年[らいねん]、二十歳[はたち]＿＿なります。",
    answer: "に",
    distractors: ["が", "で", "を"],
    translationEn: "Next year I will turn twenty.",
    level: "N4",
    note: "なる takes に for the resulting state; が would mark a subject, not the result become.",
  },
  {
    id: "pd.ni-frequency-rate",
    sentence: "一週間[いっしゅうかん]＿＿三回[さんかい]、ジムに行[い]きます。",
    answer: "に",
    distractors: ["を", "が", "へ"],
    translationEn: "I go to the gym three times a week.",
    level: "N4",
    note: "に marks the unit of time a rate is measured against ('per week'); 一週間 is neither the subject nor the object of 行く, so が and を can't attach to it.",
  },
  {
    id: "pd.ni-noru",
    sentence: "毎日[まいにち]バス＿＿乗[の]って学校[がっこう]に行[い]きます。",
    answer: "に",
    distractors: ["を", "で", "へ"],
    translationEn: "I take the bus to school every day.",
    level: "N5",
    note: "乗る takes に for the vehicle boarded; を is a common learner error carried over from English 'ride the bus.'",
  },
  {
    id: "pd.ni-tsuku-arrival",
    sentence: "電車[でんしゃ]は九時[くじ]に東京駅[とうきょうえき]＿＿着[つ]きました。",
    answer: "に",
    distractors: ["で", "へ", "を"],
    translationEn: "The train arrived at Tokyo Station at nine.",
    level: "N4",
    note: "着く pairs with に for the specific point arrived at; で marks where an action occurs, and へ sounds like general direction rather than the exact point reached.",
  },
  {
    id: "pd.ni-hairu",
    sentence: "部屋[へや]＿＿入[はい]る前[まえ]にノックしてください。",
    answer: "に",
    distractors: ["を", "で", "は"],
    translationEn: "Please knock before entering the room.",
    level: "N4",
    note: "入る takes に for the place entered — a common trap since English 'enter the room' suggests を; を would incorrectly mark 部屋 as a direct object.",
  },
  {
    id: "pd.ni-appointment-time",
    sentence: "会議[かいぎ]は午後[ごご]三時[さんじ]＿＿始[はじ]まります。",
    answer: "に",
    distractors: ["で", "へ", "を"],
    translationEn: "The meeting starts at 3pm.",
    level: "N5",
    note: "に marks the specific point in time an event begins; で marks where something happens rather than when.",
  },

  // ---------------------------------------------------------------------
  // で: instrument, material, cause, group scope
  // ---------------------------------------------------------------------
  {
    id: "pd.de-instrument-hashi",
    sentence: "はし＿＿ご飯[はん]を食[た]べます。",
    answer: "で",
    distractors: ["を", "に", "から"],
    translationEn: "I eat rice with chopsticks.",
    level: "N5",
    note: "で marks the instrument used to do an action; に would mark a location or target, not a tool.",
  },
  {
    id: "pd.de-material",
    sentence: "この机[つくえ]は木[き]＿＿できています。",
    answer: "で",
    distractors: ["に", "を", "から"],
    translationEn: "This desk is made of wood.",
    level: "N4",
    note: "で marks a material that stays visibly itself in 〜でできている; から marks a raw material that's transformed into something else (see the sake example below).",
  },
  {
    id: "pd.de-cause-typhoon",
    sentence: "台風[たいふう]＿＿電車[でんしゃ]が止[と]まりました。",
    answer: "で",
    distractors: ["に", "から", "を"],
    translationEn: "The trains stopped because of the typhoon.",
    level: "N4",
    note: "で can mark a direct cause of an event; から would mark an origin/starting point, which isn't quite the same as a direct cause here.",
  },
  {
    id: "pd.de-group-scope",
    sentence: "家族[かぞく]みんな＿＿旅行[りょこう]に行[い]きました。",
    answer: "で",
    distractors: ["に", "と", "へ"],
    translationEn: "The whole family went on a trip together.",
    level: "N4",
    note: "で marks the group acting together after みんな ('all together'); と wants a specific named companion and doesn't collocate naturally with みんな here.",
  },
  {
    id: "pd.de-tool-pencil",
    sentence: "鉛筆[えんぴつ]＿＿名前[なまえ]を書[か]いてください。",
    answer: "で",
    distractors: ["を", "に", "から"],
    translationEn: "Please write your name with a pencil.",
    level: "N5",
    note: "で marks the tool used; を would wrongly treat 鉛筆 as the direct object of 書く, when the actual object is 名前.",
  },

  // ---------------------------------------------------------------------
  // へ: direction / fixed conventions (への, から〜へ, addressing mail)
  // ---------------------------------------------------------------------
  {
    id: "pd.he-kara-e-pair",
    sentence: "この手紙[てがみ]は東京[とうきょう]から大阪[おおさか]＿＿送[おく]られました。",
    answer: "へ",
    distractors: ["に", "で", "を"],
    translationEn: "This letter was sent from Tokyo to Osaka.",
    level: "N4",
    note: "から〜へ is the fixed 'from A to B' pairing; に clashes with the から...direction already set up, and で would wrongly mark Osaka as the place of action rather than the destination.",
  },
  {
    id: "pd.he-address-convention",
    sentence: "はがきの宛先[あてさき]には「山田[やまだ]様[さま]＿＿」と書[か]きます。",
    answer: "へ",
    distractors: ["に", "で", "と"],
    translationEn: 'On a postcard, you write "To Mr. Yamada" as the addressee.',
    level: "N4",
    note: "へ is the fixed convention after a name + 様 when addressing mail; に is common in ordinary sentences but not idiomatic in this specific addressing formula.",
  },
  {
    id: "pd.he-heno-construction",
    sentence: "これは子供[こども]たち＿＿の贈[おく]り物[もの]です。",
    answer: "へ",
    distractors: ["に", "で", "と"],
    translationEn: "This is a gift for the children.",
    level: "N4",
    note: "へ combines with の (への) to modify a following noun ('a gift for X'); に cannot combine with の this way — ＊子供たちにの is ungrammatical.",
  },

  // ---------------------------------------------------------------------
  // を: direct object, and the を-marked path/departure-point pattern
  // ---------------------------------------------------------------------
  {
    id: "pd.wo-plain-yomu",
    sentence: "毎晩[まいばん]、新聞[しんぶん]＿＿読[よ]みます。",
    answer: "を",
    distractors: ["が", "に", "で"],
    translationEn: "I read the newspaper every night.",
    level: "N5",
    note: "The plain verb 読む takes を for its direct object; が would only be correct with the potential form 読める.",
  },
  {
    id: "pd.wo-object-pan",
    sentence: "朝[あさ]ごはんにパン＿＿食[た]べました。",
    answer: "を",
    distractors: ["に", "が", "で"],
    translationEn: "I ate bread for breakfast.",
    level: "N5",
    note: "を marks the direct object of 食べる; に would wrongly mark it as a location or destination.",
  },
  {
    id: "pd.wo-object-kutsu",
    sentence: "デパートで新[あたら]しい靴[くつ]＿＿買[か]いました。",
    answer: "を",
    distractors: ["に", "で", "が"],
    translationEn: "I bought new shoes at the department store.",
    level: "N5",
    note: "を marks the direct object of 買う; the shop is already marked by で earlier in the sentence, so で/に here would be wrong.",
  },
  {
    id: "pd.wo-leave-place",
    sentence: "毎朝[まいあさ]七時[しちじ]に家[いえ]＿＿出[で]ます。",
    answer: "を",
    distractors: ["に", "で", "が"],
    translationEn: "I leave home at seven every morning.",
    level: "N4",
    note: "を marks the place departed from with 出る; に would suggest 家 is a destination, and で would mark the location of an unrelated action.",
  },
  {
    id: "pd.wo-pass-through",
    sentence: "この道[みち]＿＿まっすぐ行[い]ってください。",
    answer: "を",
    distractors: ["に", "で", "が"],
    translationEn: "Please go straight along this road.",
    level: "N4",
    note: "を marks the path moved through with 行く/歩く/通る; に would mark a destination point, not the path traversed.",
  },
  {
    id: "pd.wo-request-onegai",
    sentence: "すみません、水[みず]＿＿一[ひと]つください。",
    answer: "を",
    distractors: ["が", "に", "で"],
    translationEn: "Excuse me, could I have one water, please?",
    level: "N5",
    note: "を marks the thing requested with ください; が would only fit adjectives of desire like ほしい, not the verb ください.",
  },
  {
    id: "pd.wo-benkyou",
    sentence: "大学[だいがく]で経済[けいざい]＿＿勉強[べんきょう]しています。",
    answer: "を",
    distractors: ["に", "で", "が"],
    translationEn: "I'm studying economics at university.",
    level: "N5",
    note: "を marks the direct object of する in 〜を勉強する; に would wrongly mark it as a location or target.",
  },

  // ---------------------------------------------------------------------
  // を vs が with potential / spontaneous-perception verbs
  // ---------------------------------------------------------------------
  {
    id: "pd.ga-potential-yomeru",
    sentence: "私[わたし]は漢字[かんじ]＿＿読[よ]めます。",
    answer: "が",
    distractors: ["を", "に", "へ"],
    translationEn: "I can read kanji.",
    level: "N4",
    note: "The potential form 読める takes が for its object; を is used with the plain (non-potential) verb 読む instead.",
  },
  {
    id: "pd.ga-potential-hanaseru",
    sentence: "兄[あに]は英語[えいご]＿＿話[はな]せます。",
    answer: "が",
    distractors: ["を", "に", "へ"],
    translationEn: "My older brother can speak English.",
    level: "N4",
    note: "With potential verbs like 話せる, the thing one can do takes が; を belongs with the plain verb 話す.",
  },
  {
    id: "pd.ga-dekiru-ski",
    sentence: "弟[おとうと]はスキー＿＿できます。",
    answer: "が",
    distractors: ["を", "は", "に"],
    translationEn: "My younger brother can ski.",
    level: "N5",
    note: "できる (can do) takes が for what one is able to do, not を.",
  },
  {
    id: "pd.ga-mieru-potential",
    sentence: "ここから富士山[ふじさん]＿＿見[み]えます。",
    answer: "が",
    distractors: ["を", "に", "で"],
    translationEn: "You can see Mt. Fuji from here.",
    level: "N4",
    note: "見える (can be seen) takes が for what is visible, not を.",
  },
  {
    id: "pd.ga-wakaru",
    sentence: "この問題[もんだい]の意味[いみ]＿＿分[わ]かりません。",
    answer: "が",
    distractors: ["を", "は", "に"],
    translationEn: "I don't understand the meaning of this problem.",
    level: "N4",
    note: "分かる takes が for what is/isn't understood, not を, even though English 'understand X' suggests a direct object.",
  },

  // ---------------------------------------------------------------------
  // から vs より (starting point vs comparison), plus から's other uses
  // ---------------------------------------------------------------------
  {
    id: "pd.kara-start-time",
    sentence: "授業[じゅぎょう]は九時[くじ]＿＿始[はじ]まります。",
    answer: "から",
    distractors: ["より", "に", "で"],
    translationEn: "Class starts from nine o'clock.",
    level: "N5",
    note: "から marks the starting point in time; より is for comparison ('than'), not a starting point.",
  },
  {
    id: "pd.yori-cold-comparison",
    sentence: "今日[きょう]は昨日[きのう]＿＿寒[さむ]いです。",
    answer: "より",
    distractors: ["から", "に", "で"],
    translationEn: "Today is colder than yesterday.",
    level: "N4",
    note: "より marks the standard of comparison ('than'); から marks a starting point, which doesn't fit a comparison sentence.",
  },
  {
    id: "pd.kara-origin-place",
    sentence: "この電車[でんしゃ]は大阪[おおさか]＿＿来[き]ました。",
    answer: "から",
    distractors: ["より", "に", "で"],
    translationEn: "This train came from Osaka.",
    level: "N5",
    note: "から marks the point of origin for movement; より only fits a comparison, not an origin.",
  },
  {
    id: "pd.yori-speed-comparison",
    sentence: "飛行機[ひこうき]は新幹線[しんかんせん]＿＿速[はや]いです。",
    answer: "より",
    distractors: ["から", "に", "で"],
    translationEn: "Airplanes are faster than the bullet train.",
    level: "N4",
    note: "より sets up the comparison standard for an adjective like 速い; から doesn't express comparison.",
  },
  {
    id: "pd.kara-te-form",
    sentence: "手[て]を洗[あら]って＿＿ご飯[はん]を食[た]べます。",
    answer: "から",
    distractors: ["と", "で", "に"],
    translationEn: "I eat a meal after washing my hands.",
    level: "N4",
    note: "て-form + から marks 'after doing ~'; と/で/に don't attach to the て-form to express this sequence.",
  },
  {
    id: "pd.kara-vs-de-material",
    sentence: "日本酒[にほんしゅ]は米[こめ]＿＿造[つく]られます。",
    answer: "から",
    distractors: ["で", "より", "に"],
    translationEn: "Sake is made from rice.",
    level: "N4",
    note: "から marks a raw material that undergoes a transformation into something new; で marks a material that's still visibly itself, like a desk made of wood.",
  },
  {
    id: "pd.kara-reason",
    sentence: "明日[あした]は忙[いそが]しい＿＿、早[はや]く寝[ね]ます。",
    answer: "から",
    distractors: ["と", "で", "に"],
    translationEn: "Tomorrow is busy, so I'll go to sleep early.",
    level: "N4",
    note: "から attaches after a plain-form clause to give a reason; と/で/に don't function as reason connectors in this position.",
  },
  {
    id: "pd.yori-preference-hoga",
    sentence: "忙[いそが]しい人[ひと]には、電話[でんわ]＿＿メールのほうが便利[べんり]です。",
    answer: "より",
    distractors: ["から", "で", "に"],
    translationEn: "For busy people, email is more convenient than phone calls.",
    level: "N4",
    note: "より sets up the 'than' side of a 〜のほうが comparison; から/で don't express comparison.",
  },
  {
    id: "pd.yori-height",
    sentence: "兄[あに]は父[ちち]＿＿背[せ]が高[たか]いです。",
    answer: "より",
    distractors: ["から", "で", "に"],
    translationEn: "My older brother is taller than our father.",
    level: "N4",
    note: "より marks the standard being compared against ('taller than X'); から would mark a starting point instead of a comparison.",
  },

  // ---------------------------------------------------------------------
  // まで (endpoint of time/distance, paired with から)
  // ---------------------------------------------------------------------
  {
    id: "pd.made-time-endpoint",
    sentence: "会議[かいぎ]は五時[ごじ]＿＿続[つづ]きます。",
    answer: "まで",
    distractors: ["に", "から", "で"],
    translationEn: "The meeting continues until five o'clock.",
    level: "N5",
    note: "まで marks the ending point of a duration ('until'); に marks a single point in time for a momentary action, not a span's endpoint.",
  },
  {
    id: "pd.made-distance-endpoint",
    sentence: "ここから駅[えき]＿＿歩[ある]いて十分[じゅっぷん]です。",
    answer: "まで",
    distractors: ["に", "へ", "で"],
    translationEn: "It's a ten-minute walk from here to the station.",
    level: "N4",
    note: "まで pairs with から to mark the endpoint of a measured distance; に/へ mark a destination but don't capture the from-to span.",
  },
  {
    id: "pd.kara-made-pair",
    sentence: "この店[みせ]は朝[あさ]九時[くじ]から夜[よる]十時[じゅうじ]＿＿開[あ]いています。",
    answer: "まで",
    distractors: ["に", "へ", "で"],
    translationEn: "This shop is open from 9am to 10pm.",
    level: "N5",
    note: "から〜まで is the fixed time-range pairing; に/へ/で don't mark a range endpoint.",
  },

  // ---------------------------------------------------------------------
  // の (possessive and nominalizer)
  // ---------------------------------------------------------------------
  {
    id: "pd.no-possessive-book",
    sentence: "これは私[わたし]＿＿本[ほん]です。",
    answer: "の",
    distractors: ["は", "が", "を"],
    translationEn: "This is my book.",
    level: "N5",
    note: "の marks possession between two nouns (私の本 = 'my book').",
  },
  {
    id: "pd.no-nominalizer-suki",
    sentence: "音楽[おんがく]を聞[き]く＿＿が好[す]きです。",
    answer: "の",
    distractors: ["は", "を", "に"],
    translationEn: "I like listening to music.",
    level: "N4",
    note: "の nominalizes 音楽を聞く so it can be the subject of 好き (marked by the following が); は/を can't turn a verb phrase into a noun phrase this way.",
  },
  {
    id: "pd.no-nominalizer-hajimete",
    sentence: "富士山[ふじさん]を見[み]た＿＿は初[はじ]めてです。",
    answer: "の",
    distractors: ["が", "を", "と"],
    translationEn: "This is the first time I've seen Mt. Fuji.",
    level: "N4",
    note: "の nominalizes 富士山を見た so the whole clause can be the topic marked by the following は; が/を/と don't work as nominalizers here.",
  },
  {
    id: "pd.no-possessive-kaban",
    sentence: "田中[たなか]さん＿＿かばんはとても大[おお]きいです。",
    answer: "の",
    distractors: ["は", "が", "を"],
    translationEn: "Tanaka's bag is very big.",
    level: "N5",
    note: "の links two nouns to show possession (田中さんのかばん).",
  },
  {
    id: "pd.no-pronoun-kasa",
    sentence: "この傘[かさ]は田中[たなか]さん＿＿です。",
    answer: "の",
    distractors: ["は", "が", "を"],
    translationEn: "This umbrella is Tanaka's.",
    level: "N4",
    note: "の here stands in for a possessed noun ('Tanaka's [umbrella]'), an extension of the possessive use.",
  },
  {
    id: "pd.no-nominalizer-wakaru",
    sentence: "彼[かれ]が来[こ]ない＿＿がわかりました。",
    answer: "の",
    distractors: ["は", "を", "と"],
    translationEn: "I found out that he isn't coming.",
    level: "N4",
    note: "の nominalizes 彼が来ない so it can be the subject of わかる (marked by the following が); は/を/と can't turn a clause into a noun phrase this way.",
  },

  // ---------------------------------------------------------------------
  // も (negative-of-everything patterns, "also", quantity emphasis)
  // ---------------------------------------------------------------------
  {
    id: "pd.mo-nanimo",
    sentence: "今朝[けさ]は何[なに]＿＿食[た]べませんでした。",
    answer: "も",
    distractors: ["を", "は", "が"],
    translationEn: "I didn't eat anything this morning.",
    level: "N4",
    note: "何も〜ません is the fixed 'nothing at all' pattern; を would just mark a specific object, losing the 'nothing' meaning.",
  },
  {
    id: "pd.mo-daremo",
    sentence: "教室[きょうしつ]にはだれ＿＿いませんでした。",
    answer: "も",
    distractors: ["が", "は", "を"],
    translationEn: "There was no one in the classroom.",
    level: "N4",
    note: "だれも〜ませんでした is the fixed 'no one' pattern; が would just mark a specific subject, not total absence.",
  },
  {
    id: "pd.mo-also",
    sentence: "わたしは学生[がくせい]です。田中[たなか]さん＿＿学生[がくせい]です。",
    answer: "も",
    distractors: ["は", "が", "を"],
    translationEn: "I am a student. Tanaka is also a student.",
    level: "N5",
    note: "も replaces は to mean 'also' when adding a parallel item to what was just said.",
  },
  {
    id: "pd.mo-dokomo",
    sentence: "日曜日[にちようび]はどこ＿＿行[い]きませんでした。",
    answer: "も",
    distractors: ["へ", "に", "を"],
    translationEn: "I didn't go anywhere on Sunday.",
    level: "N4",
    note: "どこも〜ませんでした is the fixed 'nowhere' pattern; へ/に would just mark a specific destination, contradicting 'didn't go anywhere.'",
  },
  {
    id: "pd.mo-quantity",
    sentence: "このパーティーには百人[ひゃくにん]＿＿来[き]ました。",
    answer: "も",
    distractors: ["が", "は", "を"],
    translationEn: "As many as a hundred people came to this party.",
    level: "N4",
    note: "も after a number emphasizes a surprisingly large quantity ('as many as'); が is a neutral subject marker without that emphasis.",
  },

  // ---------------------------------------------------------------------
  // と (companion, quoted speech/thought, exhaustive list)
  // ---------------------------------------------------------------------
  {
    id: "pd.ni-au-chance",
    sentence: "駅[えき]で偶然[ぐうぜん]、友達[ともだち]＿＿会[あ]いました。",
    answer: "に",
    distractors: ["と", "で", "を"],
    translationEn: "I happened to run into my friend at the station.",
    level: "N4",
    note: "会う takes に for someone one happens to encounter; と would suggest a mutually pre-arranged meeting, which doesn't fit 偶然 ('by chance').",
  },
  {
    id: "pd.to-au-arranged",
    sentence: "週末[しゅうまつ]、田中[たなか]さん＿＿会[あ]う約束[やくそく]をしました。",
    answer: "と",
    distractors: ["に", "を", "で"],
    translationEn: "I made plans to meet up with Tanaka this weekend.",
    level: "N4",
    note: "と frames meeting as a mutual, arranged action (with 約束 'promise'); に would frame it as one-sided encountering rather than a two-way arrangement.",
  },
  {
    id: "pd.to-companion",
    sentence: "週末[しゅうまつ]、友達[ともだち]＿＿映画[えいが]を見[み]に行[い]きます。",
    answer: "と",
    distractors: ["に", "を", "で"],
    translationEn: "This weekend I'm going to see a movie with a friend.",
    level: "N5",
    note: "と marks the companion an action is done together with; に would mark a target or destination, not a companion.",
  },
  {
    id: "pd.to-quote-omou",
    sentence: "明日[あした]は雨[あめ]が降[ふ]る＿＿思[おも]います。",
    answer: "と",
    distractors: ["を", "は", "で"],
    translationEn: "I think it will rain tomorrow.",
    level: "N4",
    note: "と marks the quoted content of 思う ('think that ~'); を would wrongly treat the clause as a plain noun object.",
  },
  {
    id: "pd.to-quote-iu",
    sentence: "田中[たなか]さんは「明日[あした]休[やす]みます」＿＿言[い]いました。",
    answer: "と",
    distractors: ["を", "は", "に"],
    translationEn: 'Tanaka said, "I will take tomorrow off."',
    level: "N4",
    note: "と marks quoted speech before 言う; を doesn't work because the quote isn't a simple noun object.",
  },
  {
    id: "pd.to-list-and",
    sentence: "机[つくえ]の上[うえ]に本[ほん]＿＿ノートがあります。",
    answer: "と",
    distractors: ["や", "も", "に"],
    translationEn: "There are a book and a notebook on the desk.",
    level: "N5",
    note: "と connects a complete, exhaustive list ('and'); や would imply an incomplete example list ('among other things').",
  },
];
